apiVersion: apps/v1
kind: Deployment
metadata:
  name: armada-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: armada
  template:
    metadata:
      labels:
        app: armada
    spec:
      containers:
        - name: armada
          image: armadak8s/armada:latest
---
apiVersion: v1
kind: Service
metadata:
  name: armada-srv
  labels:
    prometheus: cluster-monitoring
    k8s-app: kube-state-metrics
spec:
  selector:
    app: armada
  type: ClusterIP
  ports:
    - name: armada
      protocol: TCP
      port: 3030
      targetPort: 3001
# NOTE: The service account `default:default` already exists in k8s cluster.
# You can create a new account following like this:
#---
#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: <new-account-name>
#  namespace: <namespace>

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fabric8-rbac
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: default
    # Reference to upper's `metadata.namespace`
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
